baseURL = "http://www.circuidipity.com"
title = "Daniel Wayne Armstrong"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""
theme = "minimo"
rssLimit = 10
# Pagination ... default = 10
Paginate = 888
preserveTaxonomyNames = true
enableRobotsTXT = true # generate robots.txt
# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
# Enable use of emojis in content files
enableEmoji = true

[author]
name = "Daniel Wayne Armstrong"
email = "daniel@circuidipity.com"

[blackfriday]
hrefTargetBlank = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[languages]
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[permalinks]
page = "/:slug/"
posts = "/:slug/"

[taxonomies]
tag = "tags"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]

[params.copyright]
prefix = ""
holder = "Daniel Wayne Armstrong"
startYear = "2010"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "02 January 2006"
listDateFormat = "02 Jan 2006"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = false
noTermCloudShuffle = true

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "daniel@circuidipity.com"
github = "vonbrownie"
twitter = "circuidipity"

[params.social.config]
platforms = ["github","twitter","email"]

#[[menu.main]]
#name = "Home"
#weight = 1
#identifier = "Home"
#url = "/"

[[menu.main]]
name = "Posts"
weight = 20
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "Tags"
weight = 30
identifier = "tags"
url = "/tags/"

#[[menu.main]]
#name = "Projects"
#weight = 40
#identifier = "projects"
#url = "/projects/"

#[[menu.main]]
#name = "Notes"
#weight = 50
#identifier = "notes"
#url = "/notes/"

#[[menu.main]]
#name = "Colophon"
#weight = 60
#identifier = "colophon"
#url = "/colophon/"

[[menu.main]]
name = "RSS"
weight = 99
identifier = "rss"
url = "/feed.xml"
